set shell := ["fish", "-c"]

alias a := analyze

clean:
    rm -f work-obj93.cf

analyze: clean
    ghdl -a ./*.vhd

all: clean
    #!/usr/bin/env fish

    for file in *.vhd
        ghdl -a $file
    end

    for file in *_tb.vhd
        set basename (basename $file .vhd)
        ghdl -e $basename
        ghdl -r $basename --vcd=gtk_output/$basename.vcd
        echo "Test successfully created for $basename"
    end
